# Generated by Django 3.0.8 on 2021-04-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_auto_20210407_0847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
