# Generated by Django 3.1.7 on 2021-04-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0005_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='comapany_name',
            new_name='company_name',
        ),
    ]
